// src/scripts/content.ts
// Purpose: Load page.json for each album and map media filenames -> built asset URLs.
// Why: Astro/Vite can "glob import" JSON and assets at build time for static sites like GitHub Pages.

import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import path from 'node:path';
import exifr from 'exifr';
import {
  placeholderProjects,
  type PlaceholderDesign,
  type PlaceholderProject,
} from '../content/placeholders';
import { extractDominantColors, readImageDimensions } from './color-utils';
import {
  type Section,
  slugFromPath,
  filenameFromPath,
  normalizeSlugKey,
  normalizeComparablePath,
  seededRandom,
  svgDataUrl,
  buildPlaceholderPattern,
  placeholderDescription,
  rationalToNumber,
  formatDecimal,
  cleanExifString,
  stripLeadingToken,
  splitMakeAndModel,
  pickCameraFromText,
  approximateIphoneFocal,
  resolutionUnitToMM,
} from './content-utils';

export type { Section };

export interface PhotoMetadata {
  cameraMake?: string;
  cameraModel?: string;
  cameraType?: string;
  lensMake?: string;
  lensModel?: string;
  megapixels?: string;
  focalLength?: string;
  aperture?: string;
  exposureTime?: string;
  iso?: string;
}

type VideoSource = { src: string; type?: string };
type ImageItem = {
  type: 'image';
  src: string;
  webpSrc?: string;
  alt?: string;
  caption?: string;
  attribution?: string;
  meta?: PhotoMetadata;
  dominantColors?: string[];
  imageWidth?: number;
  imageHeight?: number;
};
type VideoItem = {
  type: 'video';
  sources?: VideoSource[];
  src?: string;
  poster?: string;
  caption?: string;
  alt?: string;
  attribution?: string;
};
type ModelItem = {
  type: 'model';
  src: string;   // glb
  usdz?: string; // ios
  caption?: string;
  alt?: string;
  attribution?: string;
};
export type MediaItem = ImageItem | VideoItem | ModelItem;

export interface AlbumPlaceholder {
  enabled: true;
  year: string;
  medium: string;
  dimensions: string;
  sortDate: string;
  gitignorePath: string;
  design: PlaceholderDesign;
}

export interface Album {
  title: string;
  slug: string;
  _dirSlug?: string;
  displayDate?: string;
  dateCreated?: string;
  date?: string;
  description?: string;
  cover?: string;
  coverWebp?: string;
  tags?: string[];
  media: MediaItem[];
  related?: string[];
  options?: { parallax?: boolean; bgFromDominantColor?: boolean };
  placeholder?: AlbumPlaceholder;
}

// 1) Load all page.json files per section (must be static strings for Vite)
const jsonGlobs = {
  ai: import.meta.glob('../content/ai/*/page.json', { eager: true }),
  miniature: import.meta.glob('../content/miniature/*/page.json', { eager: true }),
  graphic: import.meta.glob('../content/graphic/*/page.json', { eager: true }),
  other: import.meta.glob('../content/other/*/page.json', { eager: true }),
} as const;

// 2) Load ALL media for each section; we’ll filter by slug later.
//    `import: "default"` returns the emitted URL string for assets.
const mediaGlobs = {
  ai: import.meta.glob('../content/ai/*/media/*', { eager: true, query: '?url', import: 'default' }),
  miniature: import.meta.glob('../content/miniature/*/media/*', { eager: true, query: '?url', import: 'default' }),
  graphic: import.meta.glob('../content/graphic/*/media/*', { eager: true, query: '?url', import: 'default' }),
  other: import.meta.glob('../content/other/*/media/*', { eager: true, query: '?url', import: 'default' }),
} as const;

// 3) WebP URLs for image files. The .webp files are pre-generated by scripts/generate-webp.mjs
//    (runs as part of prebuild). We glob for *.webp with ?url just like the original media files.
const webpGlobs = {
  ai:        import.meta.glob('../content/ai/*/media/*.webp',        { eager: true, query: '?url', import: 'default' }),
  miniature: import.meta.glob('../content/miniature/*/media/*.webp', { eager: true, query: '?url', import: 'default' }),
  graphic:   import.meta.glob('../content/graphic/*/media/*.webp',   { eager: true, query: '?url', import: 'default' }),
  other:     import.meta.glob('../content/other/*/media/*.webp',     { eager: true, query: '?url', import: 'default' }),
};

const PLACEHOLDER_DEBUG = import.meta.env.DEV;
let hasLoggedPlaceholderCoverage = false;

function collectGitignoreContentPaths(): string[] {
  try {
    const gitignorePath = path.resolve(process.cwd(), '.gitignore');
    const raw = fsSync.readFileSync(gitignorePath, 'utf8');
    return raw
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.startsWith('src/content/'));
  } catch {
    return [];
  }
}

const gitignoreContentPaths = PLACEHOLDER_DEBUG ? collectGitignoreContentPaths() : [];
const gitignoreContentPathSet = new Set(gitignoreContentPaths.map(normalizeComparablePath));
const placeholderPathSet = new Set(
  placeholderProjects.map((entry) => normalizeComparablePath(entry.gitignorePath))
);
const missingPlaceholderManifestPaths = gitignoreContentPaths.filter(
  (line) => !placeholderPathSet.has(normalizeComparablePath(line))
);
const extraPlaceholderManifestPaths = placeholderProjects
  .map((entry) => entry.gitignorePath)
  .filter((line) => !gitignoreContentPathSet.has(normalizeComparablePath(line)));

function logPlaceholderCoverage() {
  if (!PLACEHOLDER_DEBUG || hasLoggedPlaceholderCoverage) return;
  const bySection = placeholderProjects.reduce<Record<string, string[]>>((acc, entry) => {
    if (!acc[entry.section]) acc[entry.section] = [];
    acc[entry.section].push(entry.slug);
    return acc;
  }, {});
  console.info('[placeholder-coverage]', {
    manifestCount: placeholderProjects.length,
    sections: bySection,
    gitignoreContentPathCount: gitignoreContentPaths.length,
    missingManifestEntries: missingPlaceholderManifestPaths,
    extraManifestEntries: extraPlaceholderManifestPaths,
  });
  hasLoggedPlaceholderCoverage = true;
}

function buildPlaceholderAlbum(entry: PlaceholderProject): Album & { _section: Section } {
  return {
    title: entry.title,
    slug: entry.slug,
    _dirSlug: entry.slug,
    displayDate: entry.year,
    dateCreated: entry.sortDate,
    date: entry.sortDate,
    description: placeholderDescription(entry.section),
    cover: buildPlaceholderPattern(entry.design),
    tags: ['catalog-placeholder'],
    media: [],
    related: [],
    options: { parallax: false, bgFromDominantColor: false },
    placeholder: {
      enabled: true,
      year: entry.year,
      medium: entry.medium,
      dimensions: entry.dimensions,
      sortDate: entry.sortDate,
      gitignorePath: entry.gitignorePath,
      design: entry.design,
    },
    _section: entry.section,
  };
}

const photoMetaCache = new Map<string, PhotoMetadata>();
const PHOTO_META_DEBUG = (() => {
  const raw = process.env.PHOTO_META_DEBUG?.trim();
  if (!raw) return false;
  return raw !== '0' && raw.toLowerCase() !== 'false';
})();

function debugPhotoMeta(label: string, payload: Record<string, unknown>) {
  if (!PHOTO_META_DEBUG) return;
  console.info(`[photo-meta] ${label}`, payload);
}

async function readPhotoMetadata(assetKey?: string): Promise<PhotoMetadata | undefined> {
  if (!assetKey) return undefined;
  if (photoMetaCache.has(assetKey)) {
    return photoMetaCache.get(assetKey);
  }
  try {
    const filePath = path.resolve(process.cwd(), 'src/scripts', assetKey);
    const buffer = await fs.readFile(filePath);
    const exif = await exifr.parse(buffer, {
      pick: [
        'Model',
        'LensModel',
        'LensMake',
        'Make',
        'FocalLength',
        'FocalLengthIn35mmFilm',
        'FocalLengthIn35mmFormat',
        'ExposureTime',
        'ISO',
        'ImageWidth',
        'ImageHeight',
        'ExifImageWidth',
        'ExifImageHeight',
        'PixelXDimension',
        'PixelYDimension',
        'ImageDescription',
        'XPKeywords',
        'FNumber',
        'ApertureValue',
        'FocalPlaneXResolution',
        'FocalPlaneYResolution',
        'FocalPlaneResolutionUnit',
      ],
    });
    if (!exif) {
      photoMetaCache.set(assetKey, {});
      return {};
    }
    const rawCameraMake = cleanExifString((exif as any).Make);
    const rawCameraModel = cleanExifString((exif as any).Model);
    const rawLensMake = cleanExifString((exif as any).LensMake);
    const rawLensModel = cleanExifString((exif as any).LensModel);
    const rawDescription = cleanExifString((exif as any).ImageDescription);
    const rawKeywords = (exif as any).XPKeywords as unknown;

    let cameraMake = rawCameraMake;
    let cameraModel = rawCameraModel;
    let lensMake = rawLensMake;
    let lensModel = rawLensModel;
    const isIphone =
      cameraModel?.toLowerCase().includes('iphone') ||
      cameraMake?.toLowerCase().includes('apple');
    let cameraType: string | undefined;
    if (isIphone && lensModel) {
      const lower = lensModel.toLowerCase();
      if (lower.includes('tele')) cameraType = 'Telephoto Camera';
      else if (lower.includes('ultra')) cameraType = 'Ultra Wide Camera';
      else if (lower.includes('front')) cameraType = 'Front Camera';
      else if (lower.includes('rear')) cameraType = 'Rear Camera';
      else cameraType = 'Back Camera';
    }

    if (!isIphone && cameraMake && cameraModel) {
      cameraModel = stripLeadingToken(cameraModel, cameraMake);
    }

    if (!isIphone && lensMake && lensModel) {
      lensModel = stripLeadingToken(lensModel, lensMake);
    }

    let lensMakeDerived = false;
    if (!isIphone && lensModel && !lensMake) {
      const split = splitMakeAndModel(lensModel);
      if (split.make) {
        lensMake = split.make;
        lensModel = split.model ?? lensModel;
        lensMakeDerived = true;
      }
    }

    if (!isIphone && (!cameraMake || !cameraModel)) {
      const fromText = pickCameraFromText(rawDescription, rawKeywords);
      const appliedFromText =
        (!cameraMake && Boolean(fromText.make)) || (!cameraModel && Boolean(fromText.model));
      if (!cameraMake && fromText.make) cameraMake = fromText.make;
      if (!cameraModel && fromText.model) cameraModel = fromText.model;
      if (appliedFromText) {
        debugPhotoMeta('camera-from-text', {
          assetKey,
          description: rawDescription,
          keywords: rawKeywords,
          cameraMake,
          cameraModel,
        });
      }
    }

    if (!isIphone && cameraMake && cameraModel) {
      cameraModel = stripLeadingToken(cameraModel, cameraMake);
    }

    if (isIphone) {
      cameraMake = undefined;
      lensMake = undefined;
      lensModel = undefined;
      debugPhotoMeta('iphone-suppress', {
        assetKey,
        rawCameraMake,
        rawCameraModel,
        rawLensMake,
        rawLensModel,
        cameraModel,
        cameraType,
      });
    } else if (cameraMake || cameraModel || lensMake || lensModel) {
      debugPhotoMeta('extracted', {
        assetKey,
        cameraMake,
        cameraModel,
        lensMake,
        lensModel,
        lensMakeDerived,
      });
    }

    const width =
      rationalToNumber(exif.ImageWidth) ??
      rationalToNumber((exif as any).ExifImageWidth) ??
      rationalToNumber((exif as any).PixelXDimension);
    const height =
      rationalToNumber(exif.ImageHeight) ??
      rationalToNumber((exif as any).ExifImageHeight) ??
      rationalToNumber((exif as any).PixelYDimension);
    const megapixels = width && height ? `${Math.round((width * height) / 1_000_000)} MP` : undefined;
    const focalLengthPhysicalRaw = rationalToNumber(exif.FocalLength);
    const focalLengthPhysical =
      typeof focalLengthPhysicalRaw === 'number' && focalLengthPhysicalRaw > 0
        ? focalLengthPhysicalRaw
        : undefined;
    const focalLength35Raw =
      rationalToNumber((exif as any).FocalLengthIn35mmFilm) ??
      rationalToNumber((exif as any).FocalLengthIn35mmFormat);
    const focalLength35 =
      typeof focalLength35Raw === 'number' && focalLength35Raw > 0 ? focalLength35Raw : undefined;
    const focalPlaneXRes = rationalToNumber((exif as any).FocalPlaneXResolution);
    const resolutionUnit = rationalToNumber((exif as any).FocalPlaneResolutionUnit);
    let equivalentFocal = focalLength35;
    if (!equivalentFocal && focalLengthPhysical && width && focalPlaneXRes) {
      const unitMM = resolutionUnitToMM(resolutionUnit);
      if (unitMM) {
        const sensorWidthMm = width * (unitMM / focalPlaneXRes);
        if (sensorWidthMm > 0) {
          equivalentFocal = focalLengthPhysical * (36 / sensorWidthMm);
        }
      }
    }
    const focalLengthNumber =
      equivalentFocal ??
      (isIphone ? approximateIphoneFocal(cameraType, focalLengthPhysical) : undefined) ??
      focalLengthPhysical;
    const focalLength = focalLengthNumber ? `${formatDecimal(focalLengthNumber)} MM` : undefined;
    const fNumber =
      rationalToNumber((exif as any).FNumber) ?? rationalToNumber((exif as any).ApertureValue);
    const aperture = fNumber ? formatDecimal(fNumber) : undefined;
    let exposureTime: string | undefined;
    const exposureRaw = rationalToNumber(exif.ExposureTime);
    if (exposureRaw && exposureRaw > 0) {
      exposureTime =
        exposureRaw >= 1
          ? `${exposureRaw.toFixed(1)}S`.replace(/\.0S$/, 'S')
          : `1/${Math.round(1 / exposureRaw)}S`;
    }
    const iso = typeof exif.ISO === 'number' ? `${exif.ISO}` : undefined;

    const meta: PhotoMetadata = {
      cameraMake,
      cameraModel,
      cameraType,
      lensMake,
      lensModel,
      megapixels,
      focalLength,
      aperture,
      exposureTime,
      iso,
    };
    photoMetaCache.set(assetKey, meta);
    return meta;
  } catch (err) {
    console.warn('Failed to read photo metadata for', assetKey, err);
    photoMetaCache.set(assetKey, {});
    return undefined;
  }
}

export function getAlbums(section: Section): (Album & { _section: Section })[] {
  logPlaceholderCoverage();
  const entries = jsonGlobs[section];
  const albumsBySlug = new Map<string, Album & { _section: Section }>();

  for (const [path, mod] of Object.entries(entries)) {
    // @ts-ignore - JSON default export
    const data: Album = (mod as any).default || (mod as any);
    const dirSlug = slugFromPath(path);
    const slug = data.slug || dirSlug;
    albumsBySlug.set(slug, { ...data, slug, _dirSlug: dirSlug, _section: section });
  }

  for (const entry of placeholderProjects) {
    if (entry.section !== section) continue;
    // Placeholder takes precedence over local files for the same slug.
    albumsBySlug.set(entry.slug, buildPlaceholderAlbum(entry));
  }

  const albums = Array.from(albumsBySlug.values());
  const sortKey = (album: Album) =>
    album.placeholder?.sortDate ||
    album.date ||
    album.dateCreated ||
    album.displayDate ||
    '';

  albums.sort((a, b) => {
    const aPlaceholder = a.placeholder?.enabled ? 1 : 0;
    const bPlaceholder = b.placeholder?.enabled ? 1 : 0;
    if (aPlaceholder !== bPlaceholder) return aPlaceholder - bPlaceholder;

    const byDate = sortKey(b).localeCompare(sortKey(a));
    if (byDate !== 0) return byDate;
    return a.title.localeCompare(b.title);
  });

  return albums;
}

export function getAlbum(section: Section, slug: string): (Album & { _section: Section }) | undefined {
  return getAlbums(section).find((a) => a.slug === slug);
}

export async function resolveAlbumMediaUrls(
  section: Section,
  slug: string,
  album: Album,
  opts: { coverOnly?: boolean } = {},
): Promise<Album> {
  const allAssets = mediaGlobs[section]; // e.g. keys like '../content/photos/sf-street/media/01.jpg'
  const mediaDirSlugKey = normalizeSlugKey(album._dirSlug ?? slug);
  // Build a small map: filename -> emitted URL + source path for THIS slug only
  const assetInfo = new Map<string, { url: string; sourcePath: string }>();
  for (const [path, url] of Object.entries(allAssets)) {
    const segments = path.split('/');
    const mediaIndex = segments.lastIndexOf('media');
    const assetDirSlug = mediaIndex > 0 ? segments[mediaIndex - 1] : '';
    if (normalizeSlugKey(assetDirSlug) !== mediaDirSlugKey) continue;
    const normalized = typeof url === 'string' ? url : String(url);
    assetInfo.set(filenameFromPath(path), { url: normalized, sourcePath: path });
  }

  // Build WebP URL map: base filename (no ext) -> hashed .webp URL for THIS slug only.
  // .webp files are pre-generated by scripts/generate-webp.mjs (runs as prebuild).
  const webpUrlByBase = new Map<string, string>();
  const allWebpAssets = webpGlobs[section];
  for (const [path, webpUrl] of Object.entries(allWebpAssets)) {
    const segments = path.split('/');
    const mediaIndex = segments.lastIndexOf('media');
    const assetDirSlug = mediaIndex > 0 ? segments[mediaIndex - 1] : '';
    if (normalizeSlugKey(assetDirSlug) !== mediaDirSlugKey) continue;
    const webpFilename = filenameFromPath(path); // e.g. "01.webp"
    const baseName = webpFilename.slice(0, -5);   // strip ".webp" → "01"
    if (typeof webpUrl === 'string') {
      webpUrlByBase.set(baseName, webpUrl);
    }
  }

  const getAssetInfo = (name?: string) => {
    if (!name) return undefined;
    return assetInfo.get(filenameFromPath(name));
  };
  const mapUrl = (name?: string) => {
    if (!name) return name;
    return getAssetInfo(name)?.url ?? name;
  };
  const mapWebpUrl = (name?: string) => {
    if (!name) return undefined;
    const filename = filenameFromPath(name);
    const dotIdx = filename.lastIndexOf('.');
    const baseName = dotIdx >= 0 ? filename.slice(0, dotIdx) : filename;
    return webpUrlByBase.get(baseName);
  };

  // Fast path: index/home pages only need the cover URL, not full per-image processing.
  // Skips all EXIF and color extraction — eliminates the main dev-mode slowness.
  if (opts.coverOnly) {
    return { ...album, cover: mapUrl(album.cover), coverWebp: mapWebpUrl(album.cover), media: [] };
  }

  const media = await Promise.all(album.media.map(async (item) => {
    if (item.type === 'image') {
      const info = getAssetInfo(item.src);
      const hasColorPalette = section === 'ai' || section === 'miniature' || section === 'other';
      const [meta, dominantColors, dims] = section === 'ai'
        ? await Promise.all([
            readPhotoMetadata(info?.sourcePath),
            extractDominantColors(info?.sourcePath),
            readImageDimensions(info?.sourcePath),
          ])
        : hasColorPalette
          ? [undefined, ...(await Promise.all([
              extractDominantColors(info?.sourcePath),
              readImageDimensions(info?.sourcePath),
            ]))]
          : [undefined, undefined, undefined];
      const itemWebpUrl = mapWebpUrl(item.src);
      return {
        ...item,
        src: info?.url ?? item.src,
        ...(itemWebpUrl ? { webpSrc: itemWebpUrl } : {}),
        meta,
        ...(dominantColors ? { dominantColors } : {}),
        ...(dims ? { imageWidth: dims.width, imageHeight: dims.height } : {}),
      };
    }
    if (item.type === 'video') {
      const explicitSources = Array.isArray((item as any).sources)
        ? (item as any).sources
        : undefined;
      const fallbackSrc = (item as any).src;

      const sources = (explicitSources && explicitSources.length > 0)
        ? explicitSources.map((s: VideoSource) => ({ ...s, src: mapUrl(s.src)! }))
        : fallbackSrc
          ? [{ src: mapUrl(fallbackSrc)! }]
          : [];

      const mappedSrc = fallbackSrc ? mapUrl(fallbackSrc)! : undefined;

      return {
        ...item,
        poster: mapUrl((item as any).poster),
        sources,
        ...(mappedSrc ? { src: mappedSrc } : {}),
      };
    }
    if (item.type === 'model') {
      return { ...item, src: mapUrl(item.src)!, usdz: mapUrl(item.usdz) };
    }
    return item;
  }));

  return {
    ...album,
    cover: mapUrl(album.cover),
    coverWebp: mapWebpUrl(album.cover),
    media,
  };
}
